# app/schemas.py
#
# =============================================================================
# CAPSTONE CONCEPT 1: Multi-agent systems built with ADK
# This file contains the Pydantic schemas that enforce structured data contracts
# and communication between the Intake, Story Planner, Decodable Writer, and
# Phonics QA/Reviser agents.
# =============================================================================

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, Field


class PhonicsProfile(BaseModel):
    """Structured intake profile capturing a student's reading capacity and interests."""

    target_level: Literal["short_vowels", "digraphs", "blends", "silent_e", "r_controlled", "vowel_teams", "glued_sounds", "y_vowel", "suffixes"] = Field(
        ..., description="The next phonics focus level we are targetting for the story."
    )
    mastered_levels: list[Literal["short_vowels", "digraphs", "blends", "silent_e", "r_controlled", "vowel_teams", "glued_sounds", "y_vowel", "suffixes"]] = Field(
        ..., description="The list of phonics levels the child has already mastered."
    )
    sight_words: list[str] = Field(
        default_factory=list,
        description="Irregular or high-frequency words the child knows (e.g., 'the', 'was')."
    )
    interest: str = Field(
        ..., description="Child's specific interest or topic for personalization, e.g., 'robots', 'dogs'."
    )
    age: int = Field(
        ..., description="Child's age, used to adapt story tone and complexity."
    )
    reading_level: str = Field(
        ..., description="General reading level category, e.g., 'early reader', 'developing reader'."
    )


class StoryOutline(BaseModel):
    """Outline designed by the Story Planner Agent, tailored to phonics limits."""

    title: str = Field(..., description="Proposed book title.")
    characters: list[str] = Field(..., description="Names of characters (should be phonics-appropriate).")
    setting: str = Field(..., description="The story setting.")
    plot_beats: list[str] = Field(
        ..., description="A list of 4-6 plot/scene beats representing pages in the storybook."
    )
    reinforcing_skills: list[str] = Field(
        ..., description="List of specific phonics sounds/patterns that will be emphasized."
    )


class StoryDraft(BaseModel):
    """The draft generated by the Decodable Writer Agent."""

    title: str = Field(..., description="The book title.")
    pages: list[str] = Field(
        ..., description="The exact text for each page of the book. Must adhere strictly to phonics limits."
    )
    notes: str = Field(
        default="", description="Writer's notes regarding word choice or phonics patterns."
    )


class QAFeedback(BaseModel):
    """Detailed report from the Phonics QA/Reviser Agent (security guardrail)."""

    is_decodable: bool = Field(
        ..., description="True if the story draft contains zero phonics or sight-word violations."
    )
    violations: list[str] = Field(
        default_factory=list,
        description="List of words in the story that violate the child's phonics profile."
    )
    feedback_report: str = Field(
        ..., description="Detailed explanation of what needs revision for the writer agent."
    )


class PageIllustration(BaseModel):
    """Illustration prompt for a single page."""

    page_number: int = Field(
        ..., description="The page number of the illustration, starting from 1."
    )
    page_text: str = Field(
        ..., description="The exact text of the story page to be illustrated."
    )
    image_prompt: str = Field(
        ..., description="A detailed, descriptive, child-friendly illustration prompt for the page, specifying consistent character appearance and style."
    )


class StoryIllustrations(BaseModel):
    """Collection of page-by-page illustration prompts for the story."""

    illustrations: list[PageIllustration] = Field(
        ..., description="List of page-by-page illustration prompts."
    )


class ExportResult(BaseModel):
    """The result of exporting the storybook to Google Docs and Google Drive."""

    doc_id: str = Field(
        ..., description="The Google Doc ID of the generated book."
    )
    shareable_url: str = Field(
        ..., description="The shareable link to the Google Doc."
    )


class ParentReport(BaseModel):
    """Report for parents containing letter, reinforced phonics patterns, and sight words to practice."""

    parent_letter: str = Field(
        ..., description="Warm, encouraging, educational note addressed to the parent."
    )
    reinforced_patterns: list[str] = Field(
        ..., description="Specific spelling rules or phonics patterns reinforced in the story (e.g. 'initial blends st-', 'digraph ch-')."
    )
    sight_words_to_practice: list[str] = Field(
        ..., description="List of high-frequency or irregular sight words from the story for parent-child practice."
    )


